build: updated Run E2E tests run

diff --git a/.github/workflows/release-nightly.yaml b/.github/workflows/release-nightly.yaml
--- a/.github/workflows/release-nightly.yaml
+++ b/.github/workflows/release-nightly.yaml
@@ -65,7 +65,13 @@ jobs:
         run: |
           cd e2e
           for target in jira-cloud jira-dc bitbucket-cloud bitbucket-dc; do
-            TARGET=$target docker compose run --rm atlascode-e2e; status=$?; docker compose down; exit $status
+            TARGET=$target docker compose run --rm atlascode-e2e
+            status=$?
+            docker compose down
+            if [ $status -ne 0 ]; then
+              echo "E2E tests failed for target: $target"
+              exit $status
+            fi
           done
 
       # - name: Publish the pre-release extension
